In [1]:
# --- IMPORT TOOLS
# Pandas for working with DataFrames
import pandas as pd
# Import numpy for high-perfomance mathematical and numerical operations
import numpy as np
# Import Matplotlib for creating charts and visualizations
import matplotlib.pyplot as plt
# Import Seaborn for creating attractive statistical visualizations with less code
import seaborn as sns

# This makes plots appear directly inside the notebook
%matplotlib inline

print("✅ Libreries loaded succesfully")

✅ Libreries loaded succesfully

In [2]:
# --- LOAD THE DATASET
# pd.read_csv() reads the file and converts it into a DataFrame.
# encoding="latin-1" is required because the file contains special characters.
df = pd.read_csv("../data/raw/sales.csv", encoding="latin-1")

# .shape returns the number of rows and columns in the DataFrame.
print(f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

The dataset has 9994 rows and 21 columns.

In [3]:
# --- PREVIEW THE DATASET
# .head(10) displays the first 10 rows of the DataFrame.
# This helps you quickly inspect the structure and contents of a new dataset.
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [4]:
# --- GENERAL INFORMATION
# .info views the "identity file" from the DataFrame
# - how many rows there is in total
# - how many columns exists
# - what kind of data type has every column(int,float,object)
# - how many values are null in every column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [5]:
# --- BASIC STATISTICS
# .describe() generates descriptive statistics for all numerical columns,
# including count, mean, standard deviation, minimum, maximum,
# and the 25th, 50th (median), and 75th percentiles.
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [6]:
# --- CHECK FOR MISSING VALUES
# .isnull() creates a boolean mask indicating missing values.
# .sum() counts the number of missing values in each column
# because True is treated as 1 and False as 0.
# The result shows the total number of NaN values per column.
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
# --- CHECK FOR EXACT DUPLICATES
# .duplicated() marks True for each row that is an exact duplicate
# of a previous row.
# .sum() counts the total number of duplicated rows.
duplicates = df.duplicated().sum()

print(f"Duplicate rows found: {duplicates}")

Duplicate rows found: 0

In [8]:
# --- CHECK DATA TYPES
# .dtypes displays the data type of each column,
# such as int64, float64, object (text), etc.
# We are especially interested in the date column.
# It is currently stored as an "object" and will be converted
# to a proper datetime type in the next step.
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [9]:
# --- CHECK FOR HIDDEN MISSING VALUES

# Select all text columns (object and string dtypes).
# Including both types avoids compatibility warnings
# between Pandas 2.x and future versions.
text_columns = df.select_dtypes(include=["object", "string"]).columns

for col in text_columns:
    # .isin() checks whether a value matches one of the
    # common placeholders used to represent missing data.
    suspicious_values = df[col].isin(
        ["N/A", "n/a", "-", "", " ", "NULL", "null"]
    ).sum()

    if suspicious_values > 0:
        print(
            f"Column '{col}': {suspicious_values} suspicious values found"
        )

print("Review completed ✅")

Review completed ✅

In [10]:
# --- CONVERT TEXT DATES TO DATETIME

# pd.to_datetime() converts a string such as "2023-11-15"
# into a proper datetime object.
# Once a column has a datetime type, pandas can extract
# components such as year, month, day, and more.
# infer_datetime_format=True tells pandas to automatically
# detect the date format.

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

# Verify that the conversion was successful.
print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [11]:
# --- CARGAR EL DATASET LIMPIO
# Siempre trabajamos desde processed/, nunca desde raw/
# parse?Dates le dice a pandas que convierta esas columnas a datetime al cargar
# asi no tenemos que hacer la conversion de nuevo

df= pd.read_csv("../data/processed/ventas_limpio.csv",
                parse_dates=["Order Date", "Ship Date"])

print(f"Dataset cargado: {df.shape[0]} filas, {df.shape[1]} columnas")

Dataset cargado: 9994 filas, 23 columnas

In [14]:
# --- TENDENCIA DE VENTAS POR ANHO
# .groupby() agrupa las filas que tienen el mismo valor en una columna
# Es como un "GROUP BY" de SQL
# .agg() define que calcular para cada grupo:
#   - Sales suma total de ventas
#   - Order ID: contamos cuantas ordenes hubo
# .reset_idex() convierte el resultado en un DataFrame normal
ventas_anuales = df.groupby("Order Year").agg(
    total_ventas = ("Sales", "sum"),
    num_ordenes = ("Order ID", "count")
).reset_index()

print(ventas_anuales)

   Order Year  total_ventas  num_ordenes
0        2014   484247.4981         1993
1        2015   470532.5090         2102
2        2016   609205.5980         2587
3        2017   733215.2552         3312

In [15]:
# ── Celda 16: Pregunta 2 — Ganancia por categoría ────────────────────
# Mismo patrón: groupby + agg
# Esta vez agrupamos por Category y calculamos la suma de Profit
# .sort_values() ordena el resultado de mayor a menor (ascending=False)

ganancia_categoria = df.groupby("Category").agg(
    Total_Ganancia=("Profit", "sum"),
    Total_Ventas=("Sales", "sum")
).reset_index().sort_values("Total_Ganancia", ascending=False)

print(ganancia_categoria)

          Category  Total_Ganancia  Total_Ventas
2       Technology     145454.9481   836154.0330
1  Office Supplies     122490.8008   719047.0320
0        Furniture      18451.2728   741999.7953